const routesNames = {
  BALANCES: "/balances",
  CLIENT: "/client",
  CLIENT_LIGA_PODIUM: "/client-liga-podium",
  COMMANDS: "/commands",
  EDIT_PLAYER: "/players/:id/edit",
  EDIT_PRODUCT: "/products/:id/edit",
  EDIT_SCHEDLE: "/schedules/:id/edit",
  EXPENSES: "/expenses",
  HOME: "/",
  LIGA_PODIUM: "/liga-podium",
  LOGIN: "/login",
  NOT_FOUND: "*",
  PLAYERS: "/players",
  PRODUCTS: "/products",
  RECOVER_PASSWORD: "/recover-password",
  SALES: "/sales",
  SCHEDULES: "/schedules",
  SETTINGS: "/settings",
  TOURNAMENT_PRIZES: "/tournament-prizes",
  TRANDING_CARDS: "/trading-cards",
  VIEW_CLIENT: "/client/:id",
  VIEW_COMMAND: "/commands/:id",
  VIEW_EXPENSE: "/expenses/:id",
  VIEW_PLAYER: "/players/:id",
  VIEM_PRODUCT: "/products/:id",
  VIEW_SALE: "/sales/:id",
  VIEW_SCHEDLE: "/schedules/:id",
  WANTED_CARDS: "/wanted-cards",
};

export default routesNames;
