const routesNames = {
  HOME: "/",
  BALANCES: "/balances",
  EXPENSES: "/expenses",
  VIEW_EXPENSE: "/expenses/:id",
  COMMANDS: "/commands",
  CLIENT: "/client",
  VIEW_CLIENT: "/client/:id",
  VIEW_COMMAND: "/commands/:id",
  TRANDING_CARDS: "/trading-cards",
  WANTED_CARDS: "/wanted-cards",
  PLAYERS: "/players",
  VIEW_PLAYER: "/players/:id",
  PRODUCTS: "/products",
  SALES: "/sales",
  LOGIN: "/login",
  SCHEDULES: "/schedules",
  VIEW_SCHEDLE: "/schedules/:id",
  EDIT_SCHEDLE: "/schedules/:id/edit",
  RECOVER_PASSWORD: "/recover-password",
  TOURNAMENT_PRIZES: "/tournament-prizes",
  LIGA_PODIUM: "/liga-podium",
  CLIENT_LIGA_PODIUM: "/client-liga-podium",
  SETTINGS: "/settings",
  NOT_FOUND: "*",
};

export default routesNames;
